### ISSUE TITLE
Question regarding `cxf_requests_seconds`

### ISSUE THREAD

**Issue by ahiggins78** [ddk-prog/prometheus#1]
A few questions about `cxf_requests_seconds`:

1) Is this a sum or avg metric?
2) Will this metric account for only successful requests?  Or all requests?

**Comment by kdprog** [comment]
Hi ahiggins78,
actually good question. Thank you.
I added histograms to collect time statistics(cxf_requests_seconds).
It is available in version 1.1.1.

**Comment by ahiggins78** [comment]
Thanks!  As a side note, I think that `counter` would be a better option than `gauge` on the three count metrics, please see [Prometheus metric types](https://prometheus.io/docs/concepts/metric_types/).

**Comment by kdprog** [comment]
Ok, thanks a lot. It doesn't seem to be critical. Accoring to [Prometheus metric types](url)  gauges are typically used for "counts", like the number of concurrent requests. This is exactly the case.
I think we can leave it as is.

**Comment by ahiggins78** [comment]
I still think counter would be better suited, but i'm ok with leaving it as gauge - thanks @kdprog !
